-Fixed: AttributeError: type object 'dataObj' has no attribute 'name' in setDataObjIndex -createDataObject: name of the datasets not indexed are now displayed when the warning is printed -dataObjectJoin: function now accept dataObj names instead of the object itself